version: "3"

services:
  postgres:
    image: postgres:15
    network_mode: bridge
    container_name: todolist_database
    volumes:
      - postgres-data:/var/lib/postgresql/data
    expose:
    - 5432
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=todolist
      - POSTGRES_DB=todolist
volumes:
  postgres-data: